### PR TITLE
Vietnamese translation for chapter 11 of the handbook

### PR DESCRIPTION
**Pull request by ngtrongkhang**
You can read my translation in html [here](https://rawgit.com/ngtrongkhang/debian-handbook/github-fork/publish/vi-VN/Debian/8/html/debian-handbook/index.html)

### CODE REVIEW

**Comment by manhnt9** [comment]
Too much changes, please split your PR.

**Comment by ngtrongkhang** [comment]
Since I found nothing in this project stating a limit on how many commits a pull request should have, it would be very helpful if you could let me know how many commits each subsequent pull request of chapter 11 should have, after I split this pull request. If that is up to me, please let me know as well.

**Comment by ngtrongkhang** [comment]
This pull request is closed for a pilot pull request just opened.

**Comment by TxGVNN** [comment]
Actually you can push directly to master if you don't want create PR. 
Everything you want to do, you always have the right.

I will take time to review your commits, thank you very much :100:

**Comment by ngtrongkhang** [comment]
Thank you for your response. In order to maximize benefits for any interested readers out there, I will push all commits related to chapter 7 and 11 to the master branch of this repository in the next few days. Then other opening pull requests may be closed as well.

**Pull request closed without merging**
